# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


r:
  - oldrel
  - release
  - devel

install:
  - Rscript -e 'devtools::install_version("dynpred", version = "0.1.2", repos = "http://cran.us.r-project.org")' # For R < 3.6
  - Rscript -e 'devtools::install_version("foreach", version = "1.4.7", repos = "http://cran.us.r-project.org")' # For R < 3.6
  - Rscript -e 'devtools::install_version("cmprsk", version = "2.2-7", repos = "http://cran.us.r-project.org")' # For R < 3.6
  - Rscript -e 'devtools::install_version("crrp", version = "1.0", repos = "http://cran.us.r-project.org")' # For R < 3.6
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')

pandoc_version: 1.19.2.1

notifications:
  email:
    on_success: change
    on_failure: change
