# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r


r:
  - release
  - devel

pandoc_version: 1.19.2.1

notifications:
  email:
    on_success: change
    on_failure: change
