# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

install:
  - ./run.sh install_aptget r-cran-rcpp r-cran-bit r-cran-ff r-cran-ffbase r-cran-rcppparallel r-cran-rcppeigen r-cran-ggplot2 r-cran-testthat r-cran-gnm r-cran-devtools
  - ./run.sh install_r drat covr microbenchmark
  - Rscript -e 'devtools::install_version("cmprsk", version = "2.2-7", repos = "http://cran.us.r-project.org")' # For R < 3.6
  - export PKG_NAME=$(Rscript -e 'cat(paste0(devtools::as.package(".")$package))')
  - export PKG_TARBALL=$(Rscript -e 'pkg <- devtools::as.package("."); cat(paste0(pkg$package,"_",pkg$version,".tar.gz"))')
